# Generated by Django 3.2.4 on 2021-06-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_nutritions_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
