# Generated by Django 3.2.4 on 2021-06-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210620_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritions',
            name='one_serving_kcal',
        ),
        migrations.AddField(
            model_name='nutritions',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
