# Generated by Django 3.2.4 on 2021-06-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210620_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritions',
            name='product',
        ),
        migrations.AddField(
            model_name='nutritions',
            name='one_serving_kca',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
