# Generated by Django 3.2.4 on 2021-06-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
