# Generated by Django 3.2.4 on 2021-06-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210620_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
