# Generated by Django 3.2.4 on 2021-06-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_allergy_allergyproduct_image_nutrition_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
