# Generated by Django 3.2.4 on 2021-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_fluid_ounce',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_ml',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='english_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='korean_name',
            field=models.CharField(max_length=45),
        ),
    ]
