# Generated by Django 3.2.4 on 2021-06-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210620_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
