# Generated by Django 3.2.4 on 2021-06-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210620_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergyproduct',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='allergyproduct',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nutrition',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Allergyproduct',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
